title: "Oncely API Documentation"
description: "API documentation with Mermaid flowcharts"
baseurl: ""
url: "https://letscubo.github.io"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
